{"name": "test_mul_004", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_case_003.Test_Credence_003 object at 0x0000014C2E502390>\n\n    def test_mul_004(self):\n        a = 3\n        b = 7\n        mul = a * b\n        print(\"Mul of a and b is :\" + str(mul))\n        if mul == 10:\n            assert True\n        else:\n>           assert False\nE           assert False\n\ntest_case_003.py:11: AssertionError"}, "start": 1690661985744, "stop": 1690661985744, "uuid": "4089d013-0b02-41ec-b5d6-d1abc4d00309", "historyId": "0d0dc4734d6416fe9a1e073a16d27166", "testCaseId": "0d0dc4734d6416fe9a1e073a16d27166", "fullName": "test_case_003.Test_Credence_003#test_mul_004", "labels": [{"name": "suite", "value": "test_case_003"}, {"name": "subSuite", "value": "Test_Credence_003"}, {"name": "host", "value": "Renu"}, {"name": "thread", "value": "54812-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case_003"}]}